# Generated by Django 5.1.3 on 2024-11-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchapp', '0007_delete_complaints'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
